
spring.application.name=zomato-backend

# MySQL Database Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/zomato
spring.datasource.username=root
spring.datasource.password=kajal
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# Server Port
server.port=8080

# JWT Secret Key
jwt.secret=yourSecretKeyForJwtAuthentication123456789

# JWT Expiration Time (24 Hours)
jwt.expiration=86400000

# Logging
logging.level.org.springframework.security=DEBUG